import SideBar from '@/components/SideBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SessionProvider from '@/components/SessionProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from '../pages/api/auth/[...nextauth]';
import Login from '@/components/Login';
import ClientProvider from '@/components/ClientProvider';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log(session);

  return (
    <html lang='en'>
      <body>
        <SessionProvider session={session}>
          {session ?
          (<div className='flex'>
            <div className='h-screen min-w-xxs bg-theme-1 overflow-y-auto text-white md:min-w-xs'>
              <SideBar />
            </div>
            <ClientProvider />
            <div className='bg-theme flex-1'>{children}</div>
          </div>
          ) : (
              <Login />
            )} 
        </SessionProvider>
      </body>
    </html>
  );
}
